=== 0xHalcyon/opnsa/corp_by_id/corps.dtd
<!ELEMENT name (year+, total_corp_all, total_industries_all)>

<!ELEMENT year (corps+, total_corp, industries+, total_industries)>

<!ELEMENT corps (alliant_tech, att, bae, boeing, booze, cali_inst, caci, comcast, comp_sci, dell, facebook, gen_atom, gen_dyn, google, harris, hp, ibm, l3, lockhead, mantech, microsoft, nat_cable, northrop, qualcomm, qwest, raytheon, saic, sra_int, unisys, united_tech, verizon)>

<!ELEMENT alliant_tech (#PCDATA)>
<!ELEMENT att (#PCDATA)>
<!ELEMENT bae (#PCDATA)>
<!ELEMENT boeing (#PCDATA)>
<!ELEMENT booze (#PCDATA)>
<!ELEMENT cali_inst (#PCDATA)>
<!ELEMENT caci (#PCDATA)>
<!ELEMENT comcast (#PCDATA)>
<!ELEMENT comp_sci (#PCDATA)>
<!ELEMENT dell (#PCDATA)>
<!ELEMENT facebook (#PCDATA)>
<!ELEMENT gen_atom (#PCDATA)>
<!ELEMENT gen_dyn (#PCDATA)>
<!ELEMENT google (#PCDATA)>
<!ELEMENT harris (#PCDATA)>
<!ELEMENT hp (#PCDATA)>
<!ELEMENT ibm (#PCDATA)>
<!ELEMENT l3 (#PCDATA)>
<!ELEMENT lockhead (#PCDATA)>
<!ELEMENT mantech (#PCDATA)>
<!ELEMENT microsoft (#PCDATA)>
<!ELEMENT nat_cable (#PCDATA)>
<!ELEMENT northrop (#PCDATA)>
<!ELEMENT qualcomm (#PCDATA)>
<!ELEMENT qwest (#PCDATA)>
<!ELEMENT raytheon (#PCDATA)>
<!ELEMENT saic (#PCDATA)>
<!ELEMENT sra_int (#PCDATA)>
<!ELEMENT unisys (#PCDATA)>
<!ELEMENT united_tech (#PCDATA)>
<!ELEMENT verizon (#PCDATA)>

<!ELEMENT total_corp (#PCDATA)>

<!ELEMENT industries (misc_defense, comp_inter, defense_aero, tele_utils, elec_utils, elec_mfg, defense_elec)>

<!ELEMENT misc_defense (#PCDATA)>
<!ELEMENT comp_inter (#PCDATA)>
<!ELEMENT defense_aero (#PCDATA)>
<!ELEMENT tele_utils (#PCDATA)>
<!ELEMENT elec_utils (#PCDATA)>
<!ELEMENT elec_mfg (#PCDATA)>
<!ELEMENT defense_elec (#PCDATA)>

<!ELEMENT total_industries (#PCDATA)>

<!ELEMENT total_corp_all (#PCDATA)>
<!ELEMENT total_industries_all (#PCDATA)>

<!ATTLIST name id CDATA #REQUIRED>
<!ATTLIST name real_name CDATA #REQUIRED>

<!ATTLIST year year CDATA #REQUIRED>

<!ATTLIST alliant_tech name CDATA #REQUIRED>
<!ATTLIST alliant_tech url CDATA #REQUIRED>

<!ATTLIST att name CDATA #REQUIRED>
<!ATTLIST att url CDATA #REQUIRED>

<!ATTLIST bae name CDATA #REQUIRED>
<!ATTLIST bae url CDATA #REQUIRED>

<!ATTLIST boeing name CDATA #REQUIRED>
<!ATTLIST boeing url CDATA #REQUIRED>

<!ATTLIST booze name CDATA #REQUIRED>
<!ATTLIST booze url CDATA #REQUIRED>

<!ATTLIST cali_inst name CDATA #REQUIRED>
<!ATTLIST cali_inst url CDATA #REQUIRED>

<!ATTLIST caci name CDATA #REQUIRED>
<!ATTLIST caci url CDATA #REQUIRED>

<!ATTLIST comcast name CDATA #REQUIRED>
<!ATTLIST comcast url CDATA #REQUIRED>

<!ATTLIST comp_sci name CDATA #REQUIRED>
<!ATTLIST comp_sci url CDATA #REQUIRED>

<!ATTLIST dell name CDATA #REQUIRED>
<!ATTLIST dell url CDATA #REQUIRED>

<!ATTLIST facebook name CDATA #REQUIRED>
<!ATTLIST facebook url CDATA #REQUIRED>

<!ATTLIST gen_atom name CDATA #REQUIRED>
<!ATTLIST gen_atom url CDATA #REQUIRED>

<!ATTLIST gen_dyn name CDATA #REQUIRED>
<!ATTLIST gen_dyn url CDATA #REQUIRED>

<!ATTLIST google name CDATA #REQUIRED>
<!ATTLIST google url CDATA #REQUIRED>

<!ATTLIST harris name CDATA #REQUIRED>
<!ATTLIST harris url CDATA #REQUIRED>

<!ATTLIST hp name CDATA #REQUIRED>
<!ATTLIST hp url CDATA #REQUIRED>

<!ATTLIST ibm name CDATA #REQUIRED>
<!ATTLIST ibm url CDATA #REQUIRED>

<!ATTLIST l3 name CDATA #REQUIRED>
<!ATTLIST l3 url CDATA #REQUIRED>

<!ATTLIST lockhead name CDATA #REQUIRED>
<!ATTLIST lockhead url CDATA #REQUIRED>

<!ATTLIST mantech name CDATA #REQUIRED>
<!ATTLIST mantech url CDATA #REQUIRED>

<!ATTLIST microsoft name CDATA #REQUIRED>
<!ATTLIST microsoft url CDATA #REQUIRED>

<!ATTLIST nat_cable name CDATA #REQUIRED>
<!ATTLIST nat_cable url CDATA #REQUIRED>

<!ATTLIST northrop name CDATA #REQUIRED>
<!ATTLIST northrop url CDATA #REQUIRED>

<!ATTLIST qualcomm name CDATA #REQUIRED>
<!ATTLIST qualcomm url CDATA #REQUIRED>

<!ATTLIST qwest name CDATA #REQUIRED>
<!ATTLIST qwest url CDATA #REQUIRED>

<!ATTLIST raytheon name CDATA #REQUIRED>
<!ATTLIST raytheon url CDATA #REQUIRED>

<!ATTLIST saic name CDATA #REQUIRED>
<!ATTLIST saic url CDATA #REQUIRED>

<!ATTLIST sra_int name CDATA #REQUIRED>
<!ATTLIST sra_int url CDATA #REQUIRED>

<!ATTLIST unisys name CDATA #REQUIRED>
<!ATTLIST unisys url CDATA #REQUIRED>

<!ATTLIST united_tech name CDATA #REQUIRED>
<!ATTLIST united_tech url CDATA #REQUIRED>

<!ATTLIST verizon name CDATA #REQUIRED>
<!ATTLIST verizon url CDATA #REQUIRED>

<!ATTLIST misc_defense name CDATA #REQUIRED>

<!ATTLIST comp_inter name CDATA #REQUIRED>

<!ATTLIST defense_aero name CDATA #REQUIRED>

<!ATTLIST tele_utils name CDATA #REQUIRED>

<!ATTLIST elec_utils name CDATA #REQUIRED>

<!ATTLIST elec_mfg name CDATA #REQUIRED>

<!ATTLIST defense_elec name CDATA #REQUIRED>

=== 0xHalcyon/opnsa/indus_by_id/400034.xml
<!-- Replace 'some_id', 'name', 'foo' for each category -->
<?xsl version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="industries.xsl"?>
<!DOCTYPE name SYSTEM "/corp_by_id/corps.dtd">
<name id="400034" real_name="Blunt, Roy">
<year year="1998">
<corps>
<alliant_tech name="Alliant Technologies" url="http://www.atk.com/">foo</alliant_tech>
<att name="AT&amp;T" url="http://www.corp.att.com/gov/">$4,500</att>
<bae name="BAE Systems" url="http://www.baesystems.com/our-company-rus/inc-businesses/intelligence-&amp;-security">foo</bae>
<boeing name="Boeing" url="http://www.boeing.com/boeing/bds/c4isr_cyber/isr/index.page">$6,500</boeing>
<booze name="Booze Allen Hamilton" url="http://www.boozallen.com/consultants/civilian-government/homeland-security-consulting/intel-operations">foo</booze>
<cali_inst name="California Institute of Technology" url="http://governmentrelations.caltech.edu/federal">foo</cali_inst>
<caci name="CACI" url="http://www.caci.com/about/hist.shtml">foo</caci>
<comcast name="Comcast, Inc" url="http://business.comcast.com/ethernet/industry-solutions/government">foo</comcast>
<comp_sci name="Computer Sciences Corporation" url="http://www.csc.com/">foo</comp_sci>
<dell name="Dell, Inc" url="http://www.dell.com/us/fedgov/p">foo</dell>
<facebook name="Facebook" url="https://www.facebook.com/about/government_requests">foo</facebook>
<gen_atom name="General Atomics" url="http://www.ga-si.com/">foo</gen_atom>
<gen_dyn name="General Dynamics" url="http://www.gd-imaging.com/Applications.xml">foo</gen_dyn>
<google name="Google, Inc" url="https://www.google.com/intl/en/policies/privacy/">foo</google>
<harris name="Harris Corporation" url="http://harris.com/products/national-intelligence.aspx">foo</harris>
<hp name="Hewlett Packard" url="http://www8.hp.com/us/en/hp-information/government-affairs/main.html">foo</hp>
<ibm name="IBM International Business Machines" url="http://researcher.watson.ibm.com/researcher/view_project.php?id=1394">foo</ibm>
<l3 name="Level 3 Communications" url="http://www.level3.com/">foo</l3>
<lockhead name="Lockheed Martin" url="http://www.lockheedmartin.com/us/what-we-do/information-technology.html">foo</lockhead>
<mantech name="Mantech International" url="http://www.mantech.com/contracts/Pages/default.aspx">foo</mantech>
<microsoft name="Microsoft" url="http://www.microsoft.com/dynamics/en/za/industries/government-contracting.aspx">foo</microsoft>
<nat_cable name="National Cable" url="https://www.ncta.com/">foo</nat_cable>
<northrop name="Northrop Grumman" url="http://www.northropgrumman.com/capabilities/c4isr/Pages/default.aspx">foo</northrop>
<qualcomm name="Qualcomm" url="http://www.qualcomm.com/about/businesses/qgov">foo</qualcomm>
<qwest name="Qwest Communications" url="http://www.centurylink.com/business/federal-gov/">foo</qwest>
<raytheon name="Raytheon" url="http://www.raytheon.com/capabilities/c4isr/">$2,000</raytheon>
<saic name="SAIC" url="http://www.saic.com/services-solutions/crisis-management-security/security-surveillance/">foo</saic>
<sra_int name="SRA International" url="http://www.sra.com/business-intelligence/">foo</sra_int>
<unisys name="Unisys" url="http://www.unisys.com/unisys/theme/index.jsp?id=16000012">foo</unisys>
<united_tech name="United Technologies" url="http://www.governmentspending.us/contractors/united-technologies-corporation/75271">foo</united_tech>
<verizon name="Verizon" url="http://business.verizonwireless.com/content/b2b/en/wireless-government.html">foo</verizon>
</corps>
<total_corp>$13,000</total_corp>
<industries>
<misc_defense name="Misc Defense">foo</misc_defense>
<comp_inter name="Computers/Internet">foo</comp_inter>
<defense_aero name="Defense Aerospace">foo</defense_aero>
<tele_utils name="Telephone Utilities">$14,000</tele_utils>
<elec_utils name="Electrical Utilities">$10,450</elec_utils>
<elec_mfg name="Electronics Manufacturing">foo</elec_mfg>
<defense_elec name="Defense Electronics">$3,000</defense_elec>
</industries>
<total_industries>$27,450</total_industries>
</year>
<year year="2000">
<corps>
<alliant_tech name="Alliant Technologies" url="http://www.atk.com/">foo</alliant_tech>
<att name="AT&amp;T" url="http://www.corp.att.com/gov/">$15,500</att>
<bae name="BAE Systems" url="http://www.baesystems.com/our-company-rus/inc-businesses/intelligence-&amp;-security">foo</bae>
<boeing name="Boeing" url="http://www.boeing.com/boeing/bds/c4isr_cyber/isr/index.page">foo</boeing>
<booze name="Booze Allen Hamilton" url="http://www.boozallen.com/consultants/civilian-government/homeland-security-consulting/intel-operations">foo</booze>
<cali_inst name="California Institute of Technology" url="http://governmentrelations.caltech.edu/federal">foo</cali_inst>
<caci name="CACI" url="http://www.caci.com/about/hist.shtml">foo</caci>
<comcast name="Comcast, Inc" url="http://business.comcast.com/ethernet/industry-solutions/government">foo</comcast>
<comp_sci name="Computer Sciences Corporation" url="http://www.csc.com/">foo</comp_sci>
<dell name="Dell, Inc" url="http://www.dell.com/us/fedgov/p">foo</dell>
<facebook name="Facebook" url="https://www.facebook.com/about/government_requests">foo</facebook>
<gen_atom name="General Atomics" url="http://www.ga-si.com/">foo</gen_atom>
<gen_dyn name="General Dynamics" url="http://www.gd-imaging.com/Applications.xml">foo</gen_dyn>
<google name="Google, Inc" url="https://www.google.com/intl/en/policies/privacy/">foo</google>
<harris name="Harris Corporation" url="http://harris.com/products/national-intelligence.aspx">foo</harris>
<hp name="Hewlett Packard" url="http://www8.hp.com/us/en/hp-information/government-affairs/main.html">foo</hp>
<ibm name="IBM International Business Machines" url="http://researcher.watson.ibm.com/researcher/view_project.php?id=1394">foo</ibm>
<l3 name="Level 3 Communications" url="http://www.level3.com/">foo</l3>
<lockhead name="Lockheed Martin" url="http://www.lockheedmartin.com/us/what-we-do/information-technology.html">foo</lockhead>
<mantech name="Mantech International" url="http://www.mantech.com/contracts/Pages/default.aspx">foo</mantech>
<microsoft name="Microsoft" url="http://www.microsoft.com/dynamics/en/za/industries/government-contracting.aspx">$7,000</microsoft>
<nat_cable name="National Cable" url="https://www.ncta.com/">$9,998</nat_cable>
<northrop name="Northrop Grumman" url="http://www.northropgrumman.com/capabilities/c4isr/Pages/default.aspx">foo</northrop>
<qualcomm name="Qualcomm" url="http://www.qualcomm.com/about/businesses/qgov">foo</qualcomm>
<qwest name="Qwest Communications" url="http://www.centurylink.com/business/federal-gov/">foo</qwest>
<raytheon name="Raytheon" url="http://www.raytheon.com/capabilities/c4isr/">foo</raytheon>
<saic name="SAIC" url="http://www.saic.com/services-solutions/crisis-management-security/security-surveillance/">foo</saic>
<sra_int name="SRA International" url="http://www.sra.com/business-intelligence/">foo</sra_int>
<unisys name="Unisys" url="http://www.unisys.com/unisys/theme/index.jsp?id=16000012">foo</unisys>
<united_tech name="United Technologies" url="http://www.governmentspending.us/contractors/united-technologies-corporation/75271">foo</united_tech>
<verizon name="Verizon" url="http://business.verizonwireless.com/content/b2b/en/wireless-government.html">$20,000</verizon>
</corps>
<total_corp>$52,498</total_corp>
<industries>
<misc_defense name="Misc Defense">foo</misc_defense>
<comp_inter name="Computers/Internet">$9,000</comp_inter>
<defense_aero name="Defense Aerospace">$6,000</defense_aero>
<tele_utils name="Telephone Utilities">$54,803</tele_utils>
<elec_utils name="Electrical Utilities">$53,606</elec_utils>
<elec_mfg name="Electronics Manufacturing">$9,000</elec_mfg>
<defense_elec name="Defense Electronics">foo</defense_elec>
</industries>
<total_industries>$132,409</total_industries>
</year>
<year year="2002">
<corps>
<alliant_tech name="Alliant Technologies" url="http://www.atk.com/">foo</alliant_tech>
<att name="AT&amp;T" url="http://www.corp.att.com/gov/">$21,000</att>
<bae name="BAE Systems" url="http://www.baesystems.com/our-company-rus/inc-businesses/intelligence-&amp;-security">foo</bae>
<boeing name="Boeing" url="http://www.boeing.com/boeing/bds/c4isr_cyber/isr/index.page">$15,000</boeing>
<booze name="Booze Allen Hamilton" url="http://www.boozallen.com/consultants/civilian-government/homeland-security-consulting/intel-operations">foo</booze>
<cali_inst name="California Institute of Technology" url="http://governmentrelations.caltech.edu/federal">foo</cali_inst>
<caci name="CACI" url="http://www.caci.com/about/hist.shtml">foo</caci>
<comcast name="Comcast, Inc" url="http://business.comcast.com/ethernet/industry-solutions/government">$9,000</comcast>
<comp_sci name="Computer Sciences Corporation" url="http://www.csc.com/">foo</comp_sci>
<dell name="Dell, Inc" url="http://www.dell.com/us/fedgov/p">foo</dell>
<facebook name="Facebook" url="https://www.facebook.com/about/government_requests">foo</facebook>
<gen_atom name="General Atomics" url="http://www.ga-si.com/">foo</gen_atom>
<gen_dyn name="General Dynamics" url="http://www.gd-imaging.com/Applications.xml">foo</gen_dyn>
<google name="Google, Inc" url="https://www.google.com/intl/en/policies/privacy/">foo</google>
<harris name="Harris Corporation" url="http://harris.com/products/national-intelligence.aspx">foo</harris>
<hp name="Hewlett Packard" url="http://www8.hp.com/us/en/hp-information/government-affairs/main.html">foo</hp>
<ibm name="IBM International Business Machines" url="http://researcher.watson.ibm.com/researcher/view_project.php?id=1394">foo</ibm>
<l3 name="Level 3 Communications" url="http://www.level3.com/">foo</l3>
<lockhead name="Lockheed Martin" url="http://www.lockheedmartin.com/us/what-we-do/information-technology.html">$9,256</lockhead>
<mantech name="Mantech International" url="http://www.mantech.com/contracts/Pages/default.aspx">foo</mantech>
