=== 0xHalcyon/opnsa/votes_by_id/votes.dtd
<!ELEMENT name (bill+)>
<!ELEMENT bill (roll, question?, source, vote, result, required)>
<!ELEMENT roll (#PCDATA)>
<!ELEMENT question (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT vote (#PCDATA)>
<!ELEMENT result (#PCDATA)>
<!ELEMENT required (#PCDATA)>
<!ATTLIST name id CDATA #REQUIRED>
<!ATTLIST name real_name CDATA #REQUIRED>
<!ATTLIST bill number CDATA #REQUIRED>
<!ATTLIST bill type CDATA #REQUIRED>
<!ATTLIST bill session CDATA #IMPLIED>
<!ATTLIST roll where CDATA #IMPLIED>
<!ATTLIST roll session CDATA #IMPLIED>
<!ATTLIST roll year CDATA #IMPLIED>
<!ATTLIST roll source CDATA #IMPLIED>
<!ATTLIST roll roll CDATA #REQUIRED>
<!ATTLIST roll datetime CDATA #REQUIRED>
<!ATTLIST roll updated CDATA #IMPLIED>
<!ATTLIST roll aye CDATA #REQUIRED>
<!ATTLIST roll nay CDATA #REQUIRED>
<!ATTLIST roll nv CDATA #REQUIRED>
<!ATTLIST roll present CDATA #REQUIRED>

=== 0xHalcyon/opnsa/votes_by_id/412599.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="votes.xsl"?>
<!DOCTYPE name SYSTEM "/votes_by_id/votes.dtd">
<name id="412599" real_name="McAllister, Vance (Rep.) [R-LA5]">
  <bill number="3362" session="113" type="h">
  <roll where="house" session="113" year="2014" roll="22" source="house.gov"
  datetime="2014-01-16T11:51:00-05:00" updated="2014-01-19T04:52:12-05:00"
  aye="186" nay="226" nv="20" present="0"/>
  <question>On Motion to Recommit with Instructions: H R 3362 To amend the Patient Protection and Affordable Care Act to require transparency in the operation of American Health Benefit Exchanges</question>
  <source>https://govtrack.us/congress/bills/113/hr3362</source>
  <vote>Nay</vote>
  <result>Failed</result>
  <required>1/2</required>
  </bill>
    <bill number="3362" session="113" type="h">
  <roll where="house" session="113" year="2014" roll="23" source="house.gov"
  datetime="2014-01-16T12:00:00-05:00" updated="2014-01-19T04:52:07-05:00"
  aye="259" nay="154" nv="19" present="0"/>
  <question>On Passage: H R 3362 To amend the Patient Protection and Affordable Care Act to require transparency in the operation of American Health Benefit Exchanges</question>
  <source>https://govtrack.us/congress/bills/113/hr3362</source>
  <vote>Yea</vote>
  <result>Passed</result>
  <required>1/2</required>
  </bill>
  </name>

=== 0xHalcyon/opnsa/votes_by_id/400629.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="votes.xsl"?>
<!DOCTYPE name SYSTEM "/votes_by_id/votes.dtd">
<name id="400629" real_name="Obama, Barack (President) [D]">
  <bill number="1927" session="110" type="s">
  <roll where="senate" session="110" year="2007" roll="309" source="senate.gov"
  datetime="2007-08-03T21:16:00-04:00" updated="2014-02-17T08:45:26-05:00"
  aye="60" nay="28" nv="12" present="0"/>
  <question>On Passage of the Bill S. 1927</question>
  <source>https://govtrack.us/congress/bills/110/s1927</source>
  <vote>Nay</vote>
  <result>Bill Passed</result>
  <required>3/5</required>
  </bill>
    <bill number="6304" session="110" type="h">
  <roll where="senate" session="110" year="2008" roll="158" source="senate.gov"
  datetime="2008-06-25T18:25:00-04:00" updated="2014-02-17T08:47:16-05:00"
  aye="80" nay="15" nv="5" present="0"/>
  <question>On Cloture on the Motion to Proceed H.R. 6304</question>
  <source>https://govtrack.us/congress/bills/110/hr6304</source>
  <vote>Not Voting</vote>
  <result>Cloture on the Motion to Proceed Agreed to</result>
  <required>3/5</required>
  </bill>
    <bill number="6304" session="110" type="h">
  <roll where="senate" session="110" year="2008" roll="164" source="senate.gov"
  datetime="2008-07-09T11:55:00-04:00" updated="2014-02-17T08:47:16-05:00"
  aye="32" nay="66" nv="2" present="0"/>
  <question>On the Amendment S.Amdt. 5064 to H.R. 6304 (Foreign Intelligence Surveillance Act of 1978)</question>
  <source>https://govtrack.us/congress/bills/110/hr6304</source>
  <vote>Yea</vote>
  <result>Amendment Rejected</result>
  <required>1/2</required>
  </bill>
    <bill number="6304" session="110" type="h">
  <roll where="senate" session="110" year="2008" roll="165" source="senate.gov"
  datetime="2008-07-09T12:20:00-04:00" updated="2014-02-17T08:47:16-05:00"
  aye="37" nay="61" nv="2" present="0"/>
  <question>On the Amendment S.Amdt. 5059 to H.R. 6304 (Foreign Intelligence Surveillance Act of 1978)</question>
  <source>https://govtrack.us/congress/bills/110/hr6304</source>
  <vote>Yea</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="6304" session="110" type="h">
  <roll where="senate" session="110" year="2008" roll="166" source="senate.gov"
  datetime="2008-07-09T12:39:00-04:00" updated="2014-02-17T08:47:16-05:00"
  aye="42" nay="56" nv="2" present="0"/>
  <question>On the Amendment S.Amdt. 5066 to H.R. 6304 (Foreign Intelligence Surveillance Act of 1978)</question>
  <source>https://govtrack.us/congress/bills/110/hr6304</source>
  <vote>Yea</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="6304" session="110" type="h">
  <roll where="senate" session="110" year="2008" roll="167" source="senate.gov"
  datetime="2008-07-09T14:17:00-04:00" updated="2014-02-17T08:47:16-05:00"
  aye="72" nay="26" nv="2" present="0"/>
  <question>On the Cloture Motion H.R. 6304</question>
  <source>https://govtrack.us/congress/bills/110/hr6304</source>
  <vote>Yea</vote>
  <result>Cloture Motion Agreed to</result>
  <required>3/5</required>
  </bill>
    <bill number="6304" session="110" type="h">
  <roll where="senate" session="110" year="2008" roll="168" source="senate.gov"
  datetime="2008-07-09T14:47:00-04:00" updated="2014-02-17T08:47:16-05:00"
  aye="69" nay="28" nv="3" present="0"/>
  <question>On Passage of the Bill H.R. 6304</question>
  <source>https://govtrack.us/congress/bills/110/hr6304</source>
  <vote>Yea</vote>
  <result>Bill Passed</result>
  <required>1/2</required>
  </bill>
    <bill number="2082" session="110" type="h">
  <roll where="senate" session="110" year="2008" roll="21" source="senate.gov"
  datetime="2008-02-13T11:06:00-05:00" updated="2014-02-17T08:47:24-05:00"
  aye="92" nay="4" nv="4" present="0"/>
  <question>On the Cloture Motion H.R. 2082</question>
  <source>https://govtrack.us/congress/bills/110/hr2082</source>
  <vote>Not Voting</vote>
  <result>Cloture Motion Agreed to</result>
  <required>3/5</required>
  </bill>
    <bill number="2082" session="110" type="h">
  <roll where="senate" session="110" year="2008" roll="22" source="senate.gov"
  datetime="2008-02-13T16:31:00-05:00" updated="2014-02-17T08:47:24-05:00"
  aye="51" nay="45" nv="4" present="0"/>
  <question>On the Conference Report H.R. 2082</question>
  <source>https://govtrack.us/congress/bills/110/hr2082</source>
  <vote>Not Voting</vote>
  <result>Conference Report Agreed to</result>
  <required>1/2</required>
  </bill>
  </name>

=== 0xHalcyon/opnsa/votes_by_id/400408.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="votes.xsl"?>
<!DOCTYPE name SYSTEM "/votes_by_id/votes.dtd">
<name id="400408" real_name="Toomey, Patrick “Pat” (Sen.) [R-PA]">
  <bill number="514" session="112" type="h">
  <roll where="senate" session="112" year="2011" roll="19" source="senate.gov"
  datetime="2011-02-15T18:08:00-05:00" updated="2014-02-17T08:53:51-05:00"
  aye="86" nay="12" nv="2" present="0"/>
  <question>On Passage of the Bill H.R. 514</question>
  <source>https://govtrack.us/congress/bills/112/hr514</source>
  <vote>Yea</vote>
  <result>Bill Passed</result>
  <required>1/2</required>
  </bill>
    <bill number="1540" session="112" type="h">
  <roll where="senate" session="112" year="2011" roll="230" source="senate.gov"
  datetime="2011-12-15T16:02:00-05:00" updated="2014-02-17T08:53:41-05:00"
  aye="86" nay="13" nv="1" present="0"/>
  <question>On the Conference Report H.R. 1540</question>
  <source>https://govtrack.us/congress/bills/112/hr1540</source>
  <vote>Yea</vote>
  <result>Conference Report Agreed to</result>
  <required>1/2</required>
  </bill>
    <bill number="990" session="112" type="s">
  <roll where="senate" session="112" year="2011" roll="81" source="senate.gov"
  datetime="2011-05-26T10:01:00-04:00" updated="2014-02-17T08:53:49-05:00"
  aye="79" nay="18" nv="3" present="0"/>
  <question>On the Cloture Motion S. 990</question>
  <source>https://govtrack.us/congress/bills/112/s990</source>
  <vote>Yea</vote>
  <result>Cloture Motion Agreed to</result>
  <required>3/5</required>
  </bill>
    <bill number="990" session="112" type="s">
  <roll where="senate" session="112" year="2011" roll="82" source="senate.gov"
  datetime="2011-05-26T16:34:00-04:00" updated="2014-02-17T08:53:49-05:00"
  aye="85" nay="10" nv="5" present="0"/>
  <question>On the Motion to Table S.Amdt. 363 to S.Amdt. 347 to S. 990 (PATRIOT Sunsets Extension Act of 2011)</question>
  <source>https://govtrack.us/congress/bills/112/s990</source>
  <vote>Yea</vote>
  <result>Motion to Table Agreed to</result>
  <required>1/2</required>
  </bill>
    <bill number="990" session="112" type="s">
  <roll where="senate" session="112" year="2011" roll="83" source="senate.gov"
  datetime="2011-05-26T17:00:00-04:00" updated="2014-02-17T08:53:49-05:00"
  aye="91" nay="4" nv="5" present="0"/>
  <question>On the Motion to Table S.Amdt. 365 to S.Amdt. 347 to S. 990 (PATRIOT Sunsets Extension Act of 2011)</question>
  <source>https://govtrack.us/congress/bills/112/s990</source>
  <vote>Yea</vote>
  <result>Motion to Table Agreed to</result>
  <required>1/2</required>
  </bill>
    <bill number="990" session="112" type="s">
  <roll where="senate" session="112" year="2011" roll="84" source="senate.gov"
  datetime="2011-05-26T17:16:00-04:00" updated="2014-02-17T08:53:49-05:00"
  aye="72" nay="23" nv="5" present="0"/>
  <question>On the Motion (Motion to Concur in the House Amendment to S. 990 with Amdt. No. 347)</question>
  <source>https://govtrack.us/congress/bills/112/s990</source>
  <vote>Yea</vote>
  <result>Motion Agreed to</result>
  <required>1/2</required>
  </bill>
    <bill number="3414" session="112" type="s">
  <roll where="senate" session="112" year="2012" roll="185" source="senate.gov"
  datetime="2012-07-26T15:23:00-04:00" updated="2014-02-17T08:55:18-05:00"
  aye="84" nay="11" nv="5" present="0"/>
  <question>On Cloture on the Motion to Proceed S. 3414</question>
  <source>https://govtrack.us/congress/bills/112/s3414</source>
  <vote>Yea</vote>
  <result>Cloture on the Motion to Proceed Agreed to</result>
  <required>3/5</required>
  </bill>
    <bill number="3414" session="112" type="s">
  <roll where="senate" session="112" year="2012" roll="187" source="senate.gov"
  datetime="2012-08-02T11:01:00-04:00" updated="2014-02-17T08:55:18-05:00"
  aye="52" nay="46" nv="2" present="0"/>
  <question>On the Cloture Motion S. 3414</question>
  <source>https://govtrack.us/congress/bills/112/s3414</source>
  <vote>Nay</vote>
  <result>Cloture Motion Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="3414" session="112" type="s">
  <roll where="senate" session="112" year="2012" roll="202" source="senate.gov"
  datetime="2012-11-14T17:37:00-05:00" updated="2014-02-17T08:55:17-05:00"
  aye="51" nay="47" nv="2" present="0"/>
  <question>On the Cloture Motion S. 3414</question>
  <source>https://govtrack.us/congress/bills/112/s3414</source>
  <vote>Nay</vote>
  <result>Cloture Motion Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="4310" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="229" source="senate.gov"
  datetime="2012-12-21T14:06:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="81" nay="14" nv="4" present="0"/>
  <question>On the Conference Report H.R. 4310</question>
  <source>https://govtrack.us/congress/bills/112/hr4310</source>
  <vote>Yea</vote>
  <result>Conference Report Agreed to</result>
  <required>1/2</required>
  </bill>
    <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="232" source="senate.gov"
  datetime="2012-12-27T17:33:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="38" nay="52" nv="10" present="0"/>
  <question>On the Amendment S.Amdt. 3437 to H.R. 5949 (FISA Amendments Act Reauthorization Act of 2012)</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Nay</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="233" source="senate.gov"
  datetime="2012-12-27T18:06:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="37" nay="54" nv="9" present="0"/>
  <question>On the Amendment S.Amdt. 3435 to H.R. 5949 (FISA Amendments Act Reauthorization Act of 2012)</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Nay</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="234" source="senate.gov"
  datetime="2012-12-27T18:26:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="12" nay="79" nv="9" present="0"/>
  <question>On the Amendment S.Amdt. 3436 to H.R. 5949 (FISA Amendments Act Reauthorization Act of 2012)</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Nay</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="235" source="senate.gov"
  datetime="2012-12-28T09:36:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="43" nay="52" nv="5" present="0"/>
  <question>On the Amendment S.Amdt. 3439 to H.R. 5949 (FISA Amendments Act Reauthorization Act of 2012)</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Yea</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="236" source="senate.gov"
  datetime="2012-12-28T10:05:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="73" nay="23" nv="4" present="0"/>
  <question>On Passage of the Bill H.R. 5949</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Yea</vote>
  <result>Bill Passed</result>
  <required>3/5</required>
  </bill>
  </name>

=== 0xHalcyon/opnsa/votes_by_id/412507.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="votes.xsl"?>
<!DOCTYPE name SYSTEM "/votes_by_id/votes.dtd">
<name id="412507" real_name="Schatz, Brian (Sen.) [D-HI]">
  <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="232" source="senate.gov"
  datetime="2012-12-27T17:33:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="38" nay="52" nv="10" present="0"/>
  <question>On the Amendment S.Amdt. 3437 to H.R. 5949 (FISA Amendments Act Reauthorization Act of 2012)</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Yea</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="233" source="senate.gov"
  datetime="2012-12-27T18:06:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="37" nay="54" nv="9" present="0"/>
  <question>On the Amendment S.Amdt. 3435 to H.R. 5949 (FISA Amendments Act Reauthorization Act of 2012)</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Yea</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="234" source="senate.gov"
  datetime="2012-12-27T18:26:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="12" nay="79" nv="9" present="0"/>
  <question>On the Amendment S.Amdt. 3436 to H.R. 5949 (FISA Amendments Act Reauthorization Act of 2012)</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Nay</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="235" source="senate.gov"
  datetime="2012-12-28T09:36:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="43" nay="52" nv="5" present="0"/>
  <question>On the Amendment S.Amdt. 3439 to H.R. 5949 (FISA Amendments Act Reauthorization Act of 2012)</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Yea</vote>
  <result>Amendment Rejected</result>
  <required>3/5</required>
  </bill>
    <bill number="5949" session="112" type="h">
  <roll where="senate" session="112" year="2012" roll="236" source="senate.gov"
  datetime="2012-12-28T10:05:00-05:00" updated="2014-02-17T08:55:16-05:00"
  aye="73" nay="23" nv="4" present="0"/>
  <question>On Passage of the Bill H.R. 5949</question>
  <source>https://govtrack.us/congress/bills/112/hr5949</source>
  <vote>Nay</vote>
  <result>Bill Passed</result>
  <required>3/5</required>
  </bill>
  </name>
