=== 0xHalcyon/opnsa/bio_by_id/bio.dtd
<!ELEMENT name (addresses, online_presence, demographics, career, committee_membership, office_staff)>

<!ELEMENT addresses (location+)>
<!ELEMENT location (address+, phone+, fax*)>
<!ELEMENT address (#PCDATA)> 
<!ELEMENT phone (#PCDATA)>
<!ELEMENT fax (#PCDATA)>

<!ELEMENT online_presence (homepage+, facebook*, twitter*, youtube?, other*)>
<!ELEMENT homepage (#PCDATA)> 
<!ELEMENT facebook (#PCDATA)>
<!ELEMENT twitter (#PCDATA)>
<!ELEMENT youtube (#PCDATA)>
<!ELEMENT other (#PCDATA)> 

<!ELEMENT demographics (alias*, born, birthplace, gender, religion*, ethnicity+, occupation+, party_affiliation, nationality+)>
<!ELEMENT alias (#PCDATA)>
<!ELEMENT born (#PCDATA)>
<!ELEMENT birthplace (#PCDATA)> 
<!ELEMENT gender (#PCDATA)>
<!ELEMENT religion (#PCDATA)>
<!ELEMENT ethnicity (#PCDATA)>
<!ELEMENT occupation (#PCDATA)> 
<!ELEMENT party_affiliation (#PCDATA)>
<!ELEMENT nationality (#PCDATA)>

<!ELEMENT career (university?, grad_school?, additional_school, first?, second?, third?, fourth?, fifth?, sixth?, seventh?, eighth?, ninth?, current+)>
<!ELEMENT university (#PCDATA)> 
<!ELEMENT grad_school (#PCDATA)>
<!ELEMENT additional_school (#PCDATA)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT second (#PCDATA)> 
<!ELEMENT third (#PCDATA)>
<!ELEMENT fourth (#PCDATA)>
<!ELEMENT fifth (#PCDATA)>
<!ELEMENT sixth (#PCDATA)> 
<!ELEMENT seventh (#PCDATA)>
<!ELEMENT eighth (#PCDATA)>
<!ELEMENT ninth (#PCDATA)>
<!ELEMENT current (#PCDATA)> 

<!ELEMENT committee_membership (committee*)>
<!ELEMENT committee (oversight_committee+, subcommittees*)>
<!ELEMENT oversight_committee (#PCDATA)>
<!ELEMENT subcommittees (subcommittee+)>
<!ELEMENT subcommittee (#PCDATA)> 

<!ELEMENT office_staff (chief, scheduler, leg_director, com_director)>
<!ELEMENT chief (#PCDATA)>
<!ELEMENT scheduler (#PCDATA)>
<!ELEMENT leg_director (#PCDATA)> 
<!ELEMENT com_director (#PCDATA)>

<!ATTLIST name id CDATA #REQUIRED>
<!ATTLIST name real_name CDATA #REQUIRED>

<!ATTLIST location name CDATA #REQUIRED>

<!ATTLIST address location CDATA #REQUIRED>

<!ATTLIST phone location CDATA #REQUIRED>

<!ATTLIST fax location CDATA #REQUIRED>

<!ATTLIST homepage name CDATA #REQUIRED>
<!ATTLIST homepage url CDATA #REQUIRED>

<!ATTLIST facebook name CDATA #REQUIRED>
<!ATTLIST facebook url CDATA #REQUIRED>

<!ATTLIST twitter name CDATA #REQUIRED>
<!ATTLIST twitter url CDATA #REQUIRED>

<!ATTLIST youtube name CDATA #REQUIRED>
<!ATTLIST youtube url CDATA #IMPLIED>

<!ATTLIST other name CDATA #REQUIRED>
<!ATTLIST other url CDATA #IMPLIED>

<!ATTLIST alias name CDATA #REQUIRED>

<!ATTLIST born name CDATA #REQUIRED>

<!ATTLIST birthplace name CDATA #REQUIRED>

<!ATTLIST gender name CDATA #REQUIRED>

<!ATTLIST religion name CDATA #REQUIRED>

<!ATTLIST ethnicity name CDATA #REQUIRED>

<!ATTLIST occupation name CDATA #REQUIRED>

<!ATTLIST party_affiliation name CDATA #REQUIRED>

<!ATTLIST nationality name CDATA #REQUIRED>

<!ATTLIST committee id CDATA #REQUIRED>
<!ATTLIST oversight_committee id CDATA #REQUIRED>
<!ATTLIST subcommittee id CDATA #REQUIRED>

<!ATTLIST chief name CDATA #REQUIRED>

<!ATTLIST scheduler name CDATA #REQUIRED>

<!ATTLIST leg_director name CDATA #REQUIRED>

<!ATTLIST com_director name CDATA #REQUIRED>

=== 0xHalcyon/opnsa/bio_by_id/test1.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="/bio_by_id/bio.xsl"?>
<!DOCTYPE name SYSTEM "/bio_by_id/bio.dtd">
<name id="name_id" real_name="name">
	<addresses>
		<location name="Washington">
			<address location="Washington">
				<![CDATA[ foo
				]]>
        	        </address>
			<phone location="Washington"> foo </phone>
			<fax location="Washington"> foo </fax>
		</location>
		<location name="District Offices">
			<address location="District Office">
				<![CDATA[ foo 
				]]>
        	        </address>
			<phone location="District Office"> foo </phone>
			<fax location="District Office"> foo </fax>
		</location>
		<location name="District Office">
			<address location="District Office">
				<![CDATA[ foo 
				]]>
                	</address>
			<phone location="District Office"> foo </phone>
			<fax location="District Office"> foo </fax>
		</location>
		<location name="District Office">
			<address location="District Office">
				<![CDATA[ foo  
				]]>
	                </address>
			<phone location="District Office"> foo </phone>
			<fax location="District Office"> foo </fax>
		</location>
		<location name="District Office">
			<address location="District Office">
				<![CDATA[ foo 
				]]>
                	</address>
			<phone location="District Office"> foo </phone>
			<fax location="District Office"> foo </fax>
		</location>
		<location name="District Office">
			<address location="District Office">
				<![CDATA[ foo 
				]]>
                	</address>
			<phone location="District Office"> foo </phone>
			<fax location="District Office"> foo </fax>
		</location>
		<location name="District Office">
			<address location="District Office">
				<![CDATA[ foo  
				]]>
	                </address>
			<phone location="District Office"> foo </phone>
			<fax location="District Office"> foo </fax>
		</location>
	</addresses>
	<online_presence>
		<homepage name="Homepage" url="foo"/>
		<facebook name="Facebook" url="foo"/>
		<twitter name="Twitter" url="foo"> @foo </twitter>
		<youtube name="YouTube" url="foo"/>
		<other name="foo" url="foo"/>
	</online_presence>
	<demographics>
		<alias name="Also Known As"> foo </alias>
		<born name="Born"> foo </born>
		<birthplace name="Birthplace"> foo </birthplace>
		<gender name="Gender"> foo </gender>
		<religion name="Religion"> foo </religion>
		<ethnicity name="Race or Ethnicity"> foo </ethnicity>
		<occupation name="Occupation"> foo </occupation>
		<party_affiliation name="Party Affiliation"> foo </party_affiliation>
		<nationality name="Nationality"> foo </nationality>
	</demographics>	
	<career>
		<university> foo </university>
		<grad_school> foo </grad_school>
		<additional_school> foo </additional_school>
		<first>  foo </first>
		<second> foo </second>
		<third> foo </third>
		<fourth> foo </fourth>
		<fifth> foo </fifth>
		<sixth> foo </sixth>
		<seventh> foo </seventh>
		<eighth>  foo </eighth>
		<ninth> foo </ninth>
		<current> foo </current>
	</career>
	<committee_membership>
		<committee id="1">
			<oversight_committee id="A"> foo </oversight_committee>
                                <subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
                                </subcommittees>
		</committee>
		<committee id="2"> 
			<oversight_committee id="B"> foo </oversight_committee>
                                <subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
                                </subcommittees>
		</committee>
		<committee id="3">
			<oversight_committee id="C"> foo </oversight_committee>
				<subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
				</subcommittees>
		</committee>
		<committee id="4">
			<oversight_committee id="D"> foo </oversight_committee>
                                <subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
                                </subcommittees>
		</committee>
		<committee id="5"> 
			<oversight_committee id="E"> foo </oversight_committee>
                                <subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
                                </subcommittees>
		</committee>
		<committee id="6">
			<oversight_committee id="F"> foo </oversight_committee>
				<subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
				</subcommittees>
		</committee>
		<committee id="7">
			<oversight_committee id="G"> foo </oversight_committee>
				<subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
				</subcommittees>
		</committee>
		<committee id="8">
			<oversight_committee id="H"> foo </oversight_committee>
                                <subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
                                </subcommittees>
		</committee>
		<committee id="9"> 
			<oversight_committee id="I"> foo </oversight_committee>
                                <subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
                                </subcommittees>
		</committee>
		<committee id="10">
			<oversight_committee id="J"> foo </oversight_committee>
				<subcommittees>
					<subcommittee id="a"> foo </subcommittee>
					<subcommittee id="b"> foo </subcommittee>
				</subcommittees>
		</committee>
	</committee_membership>
	<office_staff>
		<chief name="Chief of Staff"> foo </chief>
		<scheduler name="Scheduler"> foo </scheduler>
		<leg_director name="Legislative Director"> foo </leg_director>
		<com_director name="Communications Director"> foo </com_director>
	</office_staff>
</name>
